#!/usr/bin/env bash

set -e

ragel dnslabeltext.rl -o dnslabeltext.cc

VERSION=3.5.3-with_rrl

INCLUDES="iputils.hh arguments.hh base64.hh zoneparser-tng.hh \
rcpgenerator.hh lock.hh dnswriter.hh  dnsrecords.hh dnsparser.hh utility.hh \
recursor_cache.hh rec_channel.hh qtype.hh misc.hh dns.hh syncres.hh \
sstuff.hh mtasker.hh mtasker.cc lwres.hh logger.hh ahuexception.hh \
mplexer.hh win32_mtasker.hh win32_utility.cc ntservice.hh singleton.hh \
recursorservice.hh dns_random.hh lua-pdns.hh lua-recursor.hh namespaces.hh \
recpacketcache.hh base32.hh cachecleaner.hh json.hh rrl.hh rrl_impl.hh rrl_structures.hh"

CFILES="syncres.cc  misc.cc unix_utility.cc qtype.cc \
logger.cc arguments.cc  lwres.cc pdns_recursor.cc  \
recursor_cache.cc  dnsparser.cc dnswriter.cc  dnsrecords.cc  rcpgenerator.cc  \
base64.cc  zoneparser-tng.cc  rec_channel.cc rec_channel_rec.cc rec_control.cc \
selectmplexer.cc epollmplexer.cc kqueuemplexer.cc portsmplexer.cc pdns_hw.cc \
win32_mtasker.cc win32_rec_channel.cc win32_logger.cc ntservice.cc \
recursorservice.cc sillyrecords.cc lua-pdns.cc lua-recursor.cc randomhelper.cc \
devpollmplexer.cc recpacketcache.cc dns.cc reczones.cc base32.cc nsecrecords.cc \
dnslabeltext.cc json.cc json_ws.cc json_ws.hh rrl.cc rrl_impl.cc dns_random.cc"

cd docs
make pdns_recursor.1 rec_control.1
cd ..

DIRNAME=pdns-recursor-$VERSION
rm -rf $DIRNAME
mkdir  $DIRNAME
cp $INCLUDES $CFILES $DIRNAME
cp Makefile-recursor $DIRNAME/Makefile
cp Makefile-recursor.win32 $DIRNAME/Makefile.win32
cp README-recursor $DIRNAME/README
cp ../COPYING $DIRNAME/
cp config-recursor.h $DIRNAME/config-recursor.h
mkdir -p $DIRNAME/ext/rapidjson/include/rapidjson/internal
cp -a ext/rapidjson/include/rapidjson/*.h $DIRNAME/ext/rapidjson/include/rapidjson/
cp -a ext/rapidjson/include/rapidjson/internal/*.h $DIRNAME/ext/rapidjson/include/rapidjson/internal
mkdir -p $DIRNAME/ext/polarssl-1.3.2/include/polarssl
cp -a ext/polarssl-1.3.2/include/polarssl/*.h $DIRNAME/ext/polarssl-1.3.2/include/polarssl/
mkdir -p $DIRNAME/ext/polarssl-1.3.2/library
cp -a ext/polarssl-1.3.2/library/*.c $DIRNAME/ext/polarssl-1.3.2/library/
mkdir $DIRNAME/rrd
cp tools/rrd/{create,update,makegraphs,index.html} $DIRNAME/rrd
mkdir -p $DIRNAME/aes
cp -f aes/*.{c,h} $DIRNAME/aes
cp pdns-recursor.init.d $DIRNAME
mkdir -p $DIRNAME/docs
cp docs/pdns_recursor.1 docs/rec_control.1 $DIRNAME/docs
cp configure-recursor $DIRNAME/configure
cp powerdns-example-script.lua $DIRNAME
mkdir -p $DIRNAME/contrib
cp ../contrib/systemd-pdns-recursor.service $DIRNAME/contrib

mkdir -p $DIRNAME/sysdeps
cp "PowerDNS Recursor.vcproj" $DIRNAME/

mkdir $DIRNAME/sysdeps-recursor/
rm -f sysdeps-recursor/*~
cp -r sysdeps-recursor/ $DIRNAME/


